name: TestContainers Action
run-name: testcontainers running on github actions ðŸš€
on: [push]
jobs:
  RunIntegrationTest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ Let's start testing"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Test With testcontainers
        run: go test ./ratelimit -v
